# Generated by Django 6.0.1 on 2026-01-17 09:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('alternate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('alternate_phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('primary_country_code', models.CharField(choices=[('+91', 'India'), ('+1', 'USA'), ('+44', 'UK'), ('+61', 'Australia'), ('+81', 'Japan'), ('+49', 'Germany'), ('+86', 'China'), ('+33', 'France'), ('+7', 'Russia'), ('+971', 'UAE')], default='+91', max_length=5)),
                ('alternate_country_code', models.CharField(choices=[('+91', 'India'), ('+1', 'USA'), ('+44', 'UK'), ('+61', 'Australia'), ('+81', 'Japan'), ('+49', 'Germany'), ('+86', 'China'), ('+33', 'France'), ('+7', 'Russia'), ('+971', 'UAE')], default='+91', max_length=5)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('card_brand', models.CharField(max_length=20)),
                ('card_number', models.CharField(max_length=16)),
                ('card_holder_name', models.CharField(max_length=150)),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('friend', 'Friend'), ('other', 'Other')], max_length=10)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(choices=[('IN', 'India'), ('US', 'United States'), ('UK', 'United Kingdom'), ('AU', 'Australia'), ('JP', 'Japan'), ('DE', 'Germany'), ('FR', 'France')], default='IN', max_length=2)),
                ('state', models.CharField(choices=[('MH', 'Maharashtra'), ('DL', 'Delhi'), ('KA', 'Karnataka'), ('CA', 'California'), ('NY', 'New York'), ('TX', 'Texas'), ('LN', 'London')], default='MH', max_length=3)),
                ('city', models.CharField(choices=[('MUM', 'Mumbai'), ('BLR', 'Bangalore'), ('DEL', 'Delhi'), ('LA', 'Los Angeles'), ('NYC', 'New York City'), ('LDN', 'London')], default='MUM', max_length=4)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='profiles.userprofile')),
            ],
            options={
                'unique_together': {('user', 'address_type')},
            },
        ),
    ]
