# Generated by Django 6.0.1 on 2026-01-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('MUM', 'Mumbai'), ('BLR', 'Bangalore'), ('DEL', 'Delhi'), ('LA', 'Los Angeles')], default='MUM', max_length=4),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'USA'), ('UK', 'UK'), ('AU', 'Australia'), ('JP', 'Japan')], default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('MH', 'Maharashtra'), ('DL', 'Delhi'), ('KA', 'Karnataka'), ('CA', 'California')], default='MH', max_length=3),
        ),
    ]
